export enum TaskType {
    LAUNCH_BROWSER = "LAUNCH_BROWSER",
    PAGE_TO_HTML = "PAGE_TO_HTML",
    EXTRACT_TEXT_FROM_ELEMENT = "EXTRACT_TEXT_FROM_ELEMENT",
    FILL_INPUT = "FILL_INPUT",
    CLICK_ELEMENT = "CLICK_ELEMENT",
    WAIT_FOR_ELEMENT = "WAIT_FOR_ELEMENT",
    SCROLL_TO_ELEMENT = "SCROLL_TO_ELEMENT",
    NAVIGATE_URL = "NAVIGATE_URL",
    EXTRACT_DATA_WITH_AI = "EXTRACT_DATA_WITH_AI",
    READ_PROPERTY_FROM_JSON = "READ_PROPERTY_FROM_JSON",
    ADD_PROPERTY_TO_JSON = "ADD_PROPERTY_TO_JSON",
    MERGE_TWO_JSON = "MERGE_TWO_JSON",
    DELIVER_VIA_WEBHOOK = "DELIVER_VIA_WEBHOOK",
}

export enum TaskParamType {
    STRING = "STRING",
    SELECT = "SELECT",
    CREDENTIAL = 'CREDENTIAL',
    AGENT = 'AGENT',
    BROWSER_INSTANCE = "BROWSER_INSTANCE"
}

export interface TaskParam {
    name: string
    type: TaskParamType
    helperText?: string
    require?: boolean
    hideHandle?: boolean
    [key: string]: any
} 