export enum TaskType {
    LAUNCH_BROWSER = "LAUNCH_BROWSER",
    PAGE_TO_HTML = "PAGE_TO_HTML",
    EXTRACT_TEXT_FROM_ELEMENT = "EXTRACT_TEXT_FROM_ELEMENT",
    FILL_INPUT = "FILL_INPUT",
    CLICK_ELEMENT = "CLICK_ELEMENT",
    WAIT_FOR_ELEMENT = "WAIT_FOR_ELEMENT",
    SCROLL_TO_ELEMENT = "SCROLL_TO_ELEMENT",
    NAVIGATE_URL = "NAVIGATE_URL",
    PROCESS_DATA_WITH_OPEN_AI = "PROCESS_DATA_WITH_OPEN_AI",
    READ_PROPERTY_FROM_JSON = "READ_PROPERTY_FROM_JSON",
    ADD_PROPERTY_TO_JSON = "ADD_PROPERTY_TO_JSON",
    MERGE_TWO_JSON = "MERGE_TWO_JSON",
    EXECUTE_REQUEST = "EXECUTE_REQUEST",
    DELIVER_VIA_WEBHOOK = "DELIVER_VIA_WEBHOOK",
    TRIGGER_ACTION_ON_CONDITION = "TRIGGER_ACTION_ON_CONDITION",
}

export enum TaskParamType {
    STRING = "STRING",
    BOOLEAN = "BOOLEAN",
    SELECT = "SELECT",
    CREDENTIAL = 'CREDENTIAL',
    PARAMETERS = 'PARAMETERS',
    ENCRYPTED_PROPERTIES = 'ENCRYPTED_PROPERTIES',
    AGENT = 'AGENT',
    BROWSER_INSTANCE = "BROWSER_INSTANCE"
}

export interface TaskParam {
    name: string
    type: TaskParamType
    helperText?: string
    require?: boolean
    hideHandle?: boolean
    [key: string]: any
} 